name: careerlens
version: "1.0.0"
config-version: 2

profile: careerlens

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  careerlens:
    staging:
      +materialized: view
    marts:
      +materialized: table
